image:
  repository: maxmorhardt/topfilms-primary-api
  tag: '1.0.0'
  pullPolicy: Always
  replicas: 1
  revisionHistoryLimit: 2
  env:
    - name: DATASOURCE_URL
      valueFrom:
        secretKeyRef:
          name: primary-api-env
          key: datasourceUrl
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: primary-api-env
          key: dbUsername
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: primary-api-env
          key: dbPassword
  readinessProbe:
    path: /monitor/health
    initialDelaySeconds: 150
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5
    successThreshold: 1
  livenessProbe:
    path: /monitor/health
    initialDelaySeconds: 150
    periodSeconds: 30
    timeoutSeconds: 30
    failureThreshold: 5
    successThreshold: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: api.topfilms.io
      paths:
        - path: /
          pathType: Prefix
  tls: 
   - secretName: api.topfilms.io-tls
     hosts:
       - api.topfilms.io

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPU: 80

resources:
  limits:
    cpu: 750m
    memory: 512Mi
  requests:
    cpu: 500m
    memory: 256Mi
